"""
Student Table Model

Defines the `Student` table with core fields and validation logic.
"""

from typing import Optional

from fastapi.openapi.models import Contact
from pydantic import model_validator
from sqlalchemy import ForeignKey, Column, Integer
from sqlmodel import Field, SQLModel

from v1.utils import verif_str, verif_tel_number


class Student(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True, index=True)
    name: str = Field(..., nullable=False)
    tel1: str = Field(..., max_length=8, nullable=False)
    tel2: str = Field(..., max_length=8, nullable=False)

    # FK to QRCode table with cascade on delete/update
    qrcode: Optional[int] = Field(
        default=None,
        sa_column=Column(
            Integer,
            ForeignKey("qrcode.id", ondelete="CASCADE", onupdate="CASCADE"),
            nullable=True,
        ),
    )

    @model_validator(mode="after")
    @classmethod
    def not_empty(self, m: "Contact") -> "Contact":
        """
        Validates that:
        - No autogenerated (`id`) or FK (`qrcode`) fields were provided
        - All required fields (`name`, `tel1`, `tel2`) are present
        - `name`, `tel1`, and `tel2` each meet their format requirements
        - `tel1` and `tel2` are not identical
        """

        missing = [f for f in ("name", "tel1", "tel2") if getattr(m, f) is None]
        if getattr(m, "id") or getattr(m, "qrcode"):
            raise ValueError(f"id and qrcode fields are forbidden.")
        if missing:
            raise ValueError(f"Missing required fields: {', '.join(missing)}")
        if not verif_str(getattr(m, "name")):
            raise ValueError("Name does not meet requirements")
        if not verif_tel_number(getattr(m, "tel1")):
            raise ValueError("Telephone number 1 does not meet requirements")
        if not verif_tel_number(getattr(m, "tel2")):
            raise ValueError("Telephone number 2 does not meet requirements")
        if getattr(m, "tel1") == getattr(m, "tel2"):
            raise ValueError("Telephone numbers should not match")
        return m
